const directoryActionTypes = {
  FETCH_DIRECTORY_START: 'FETCH_DIRECTORY_START',
  FETCH_DIRECTORY_SUCCESS: 'FETCH_DIRECTORY_SUCCESS',
  FETCH_DIRECTORY_FAILURE: 'FETCH_DIRECTORY_FAILURE',
};

export default directoryActionTypes;
